Hw 34 solution
ipantazi/jv-online-book-store pull request #1
Opened 2024-09-29 20:45 UTC by ipantazi

Added `Book` entity, `DataProcessingException` class, `BookRepository` interface with methods and `BookRepositoryImpl` class.
Added `BookService` interface with methods and `BookServiceImpl` class.
Modified `Application` class and file `application.properties`.
Created a new folder `resources` in the `src/test` directory
Create a new file `application.properties` in the `src/test/resources` folder.
Added dependencies to the `pom.xml` file.

2024-09-30 12:11 UTC, Elena-Bruyako requested changes
see comments

2024-09-30 12:11 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>commons-dbcp</artifactId>
Why do you need such dependency?

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/Application.java
> +            Book macbeth = new Book();
```suggestion
            Book book = new Book();
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/Application.java
> +            macbeth.setIsbn("978-0091547714");
set up all fields

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +@Data
Don't use `@Data` for entities, find and read articles about problems
Lombok has a lot of other annotations that replace boilerplate code
Don't forget to add Table annotation, to specify the name of table according to the naming convention

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    private String title;
add required constraints for fields

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/repository/BookRepository.java
> +
```suggestion
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/repository/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +    }
```suggestion
```

2024-09-30 12:11 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/my_db?serverTimezone=UTC
it's better to rename schema according to your project (don't be so abstract)

2024-10-01 11:39 UTC, Elena-Bruyako requested changes
see comments

2024-10-01 11:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    public final boolean equals(Object o) {
remove

2024-10-01 11:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    public int hashCode() {
remove

2024-10-01 11:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +@AllArgsConstructor
```suggestion
```

2024-10-01 11:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +@Builder
do you use builder somewhere? If no - remove

2024-10-01 11:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @Column(name = "title", nullable = false)
```suggestion
    @Column(nullable = false)
```

for all fields

2024-10-07 09:05 UTC, ahoienko approved these changes
Good job!

2024-11-23 01:37 UTC, closed without merging