Hw 38 solution
ipantazi/jv-online-book-store pull request #3
Opened 2024-11-18 01:57 UTC by ipantazi

2024-11-18 09:43 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes ;)

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    public int updateBook(@PathVariable Long id,
```suggestion
    public BookDto updateBook(@PathVariable Long id,
```
Better return updated book

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    private boolean deleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/repository/BookRepository.java
> +                        @Param("coverImage") String coverImage);
Why do you need it? Can you use the method save CrudRepository?

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +                bookRequestDto.getCoverImage());
Use Mapper for it;) Check if the book exists before updating

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +    public void deleteById(Long id) {
the same. Let’s check that the book exists by id.

2024-11-18 09:43 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +
leave one empty line at the end of the file

2024-11-20 12:42 UTC, Elena-Bruyako requested changes
see comments

2024-11-20 12:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
check if `@Where` is deprecated or not

2024-11-20 12:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @Column(name = "is_deleted", nullable = false)
```suggestion
    @Column(nullable = false)
    private String coverImage;

    @Column(nullable = false)
```

2024-11-20 12:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/service/BookServiceImpl.java
> +        bookRepository.save(updatedBook);
```suggestion
        Book book = findBookById(Long id);
        bookMapper.updateBookFromDto(bookRequestDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-11-20 12:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/mapper/BookMapper.java
> +    Book updateBookFromDto(CreateBookRequestDto bookRequestDto, @MappingTarget Book book);
```suggestion
    void updateBookFromDto(CreateBookRequestDto bookRequestDto, @MappingTarget Book book);
```

2024-11-23 11:21 UTC, Elena-Bruyako requested changes
two comments

2024-11-23 11:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @Column(nullable = false)
```suggestion
```

2024-11-23 11:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/model/Book.java
> +    @Column(nullable = false)
```suggestion
```

2024-11-24 11:22 UTC, Elena-Bruyako requested changes
don't forget about changesets when you make some changes in entity

2024-11-24 11:22 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
```

2024-11-24 11:22 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
```

2024-11-25 08:36 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments;)

2024-11-25 08:36 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/dto/BookDto.java
> +@RequiredArgsConstructor
Why do you need this annotation here?

2024-11-25 08:36 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
> +@RequiredArgsConstructor
the same

2024-12-10 20:50 UTC, closed without merging