GlobalExceptionHandler and data validation.
ipantazi/jv-online-book-store pull request #7
Opened 2024-12-12 16:28 UTC by ipantazi

Added `CustomGlobalExceptionHandler` class.
Added dependency `validation` to the `pom.xml`.
Added validation for DTO classes.

2024-12-12 17:24 UTC, Elena-Bruyako requested changes
see comments

2024-12-12 17:24 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    public List<BookDto> searchBooks(@Validated BookSearchParametersDto searchParameters) {
```suggestion
    public List<BookDto> searchBooks(@Valid BookSearchParametersDto searchParameters) {
```

2024-12-12 17:24 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Validated CreateBookRequestDto bookRequestDto) {
```suggestion
    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto bookRequestDto) {
```

2024-12-12 17:24 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/controller/BookController.java
> +                              @RequestBody @Validated CreateBookRequestDto bookRequestDto) {
```suggestion
                              @RequestBody @Valid CreateBookRequestDto bookRequestDto) {
```

2024-12-13 13:56 UTC, JJJazl approved these changes

2024-12-13 13:57 UTC, JJJazl commented
Please, pay attention that you have merge conflicts. Be careful and resolve it properly to avoid challenges with your next PRs

2024-12-13 16:29 UTC, merged